### ISSUE TITLE
this.scrollbar.setOptions is not a function

### ISSUE THREAD

**Issue by emko4** [idiotWu/react-smooth-scrollbar#16]
When props change, scrollbar crash in **componentWillReceiveProps** method.

`componentWillReceiveProps(nextProps) {
    this.scrollbar.setOptions(nextProps);
}`

Also I can't find **setOptions** function in smooth-scrollbar package.

**Comment by dolphin-wood** [comment]
Yep, it has been removed since 8.0. You can use `scrollbar.options.[whatever] = xxx` instead.

Sorry for the inconvenience.

**Comment by dolphin-wood** [comment]
Oh sorry I misread the issue. I'll fix right after I get back to my computer 🙇

**Comment by emko4** [comment]
Thanks for such a quick response 😄 👍

**Comment by dolphin-wood** [comment]
A patch version is published, try

```
npm update react-smooth-scrollbar smooth-scrollbar
```

to fix this issue.

Please let me know if it couldn't be resolved :)
