### ISSUE TITLE
Uncaught DOMException: Failed to execute 'removeChild'

### ISSUE THREAD

**Issue by emko4** [idiotWu/react-smooth-scrollbar#17]
I think, that problem is in render method:

`{children.length > 1 ? <div>{children}</div> : children}`

Everything is correct, when `<div />` or other HTML element ( or elements) is (are) used like content. But when other React component is used error from title is thrown. Even if component has one root `<div />` element.

**Comment by dolphin-wood** [comment]
May be something similar to #9 ?

**Comment by dolphin-wood** [comment]
A possible fix to this issue is to wrap `children` with a `<div>` element regardless of `children.length`:

```js
<section data-scrollbar ref={element => this.$container = element} {...others}>
  <div>{children}</div>
</section>
```

But the problem then is that a useless `<div>` is inserted into the DOM.

**Comment by emko4** [comment]
I'm sorry. Yes, that same issue. I will fix it with "useless" div. Thanks

**Comment by dolphin-wood** [comment]
Just wondering if I should use the "useless" `div` in react-smooth-scrollbar. Or is there any better way to solve this problem?

**Comment by emko4** [comment]
I didn't see DOM manipulation in smooth-scrollbar, but maybe you could use [React children API](https://reactjs.org/docs/react-api.html#reactchildren)? (count, etc.)

Maybe use wrap div only if there is more childrens (React.Children.count) and if there is only one, get reference of component element. 

But I really don't know if it will be helpful.

**Comment by dolphin-wood** [comment]
I've tried serval resolutions like the portal tricks, but it seems to be best with the "useless" `div` wrapper 😞 .

Will publish a patch release soon.
