### ISSUE TITLE
Jsx?

### ISSUE THREAD

**Issue by pdrozdowski** [idiotWu/react-smooth-scrollbar#2]
Just wondering does that make sense to pull in all the JSX tools just to make 3 lines in it :)

**Comment by dolphin-wood** [comment]
Aha actually I am not familiar with react and I don't know what exactly `JSX tools` stands for...I've googled but still confused :(

**Comment by pdrozdowski** [comment]
JSX allows that fancy tag-like sytax you do have in render method of react component. babel which you have on dev dependencies list does the translation of it into pure javascript during compilation/bundling. I see you not sure whats it so better to leave as is. Regards

**Comment by pdrozdowski** [comment]
One more thing, if someone is making a mor complex com

**Comment by pdrozdowski** [comment]
Sorry, hit close accidentally in middle of the comment. So what I wanted to say is that if you are building more complex component using yours then it is required to have jsx support in toolchain which might be unfortunate in some circumstances. Of course one could include your as an external instead of bundling but that adds additional effort to end used / dev.

**Comment by dolphin-wood** [comment]
So i guess you meant the jsx source files? It can be found [here](https://github.com/idiotWu/react-smooth-scrollbar/blob/master/src/react-smooth-scrollbar.jsx), under the `src/` dir.
