### ISSUE TITLE
Scrollbar.setPosition() doesn't work on componentDidMount?

### ISSUE THREAD

**Issue by Okami92** [idiotWu/react-smooth-scrollbar#20]
Hi. Could someone please help me with issue of setting initial position when component mounts? for some reason it works only when I add this method in click event http://prntscr.com/hh6e71

Also I've noticed that when component mounts, limit is 0 on both axis and it receives value only when I scroll, for example, so that's I guess the reason for setPosition not working, even with hardcoded data, like (100, 100).

**Comment by dolphin-wood** [comment]
>  limit is 0 on both axis 

If so, I think you can try `scrollbar.update()` before calling `setPosition`.

**Comment by Okami92** [comment]
Thanks for quick response!

Actually, while testing component, I found something fascinating for me.

this is portion of component with Scrollbar http://prntscr.com/hh964o

1) when I am doing `console.log(scrollbar.limit);` in cDM, I receive this in console `{x: Infinity, y: Infinity}`

2) with this 
`scrollbar.update();
    console.log(scrollbar.limit);`
I receive `{x: 0, y: 0}`

3) and only when I logging the whole scrollbar object `console.log(scrollbar);`, I receive http://prntscr.com/hh98dk

This is the first time I see something like that 0_0

**Comment by dolphin-wood** [comment]
I'm wondering if you're loading stylesheets after scripts? It seems that the styles are applied to DOM after `componentDidMount` calls, which results in the wrong metrics.

**Comment by dolphin-wood** [comment]
Similar issue: https://github.com/idiotWu/smooth-scrollbar/issues/106#issuecomment-337233906

**Comment by dolphin-wood** [comment]
A little trick for issues like this: (not sure it will work)

```js
requestAnimationFrame(() => {
    console.log(scrollbar.limit);
});
```

**Comment by Okami92** [comment]
Unfortunately it still returns `{x: 0, y: 0}` :(

regarding styles - if it was really the case, would I still be able to see limit in logging full object in cDM?

**Comment by dolphin-wood** [comment]
Yeah console interface executes only when you're clicking to expand a property, so what you see in `console.log(scrollbar)` is a kind of delayed data.

Just a little check to ensure this issue is related to styles: are you using `style-loader` with `sourceMap: true` to bundle css into a js file?

**Comment by Okami92** [comment]
Yes, that's right. I rewrote webpack configuration with ExtractTextPlugin and now it works. Thanks a lot for helping me in understanding of this confusion! I didn't know that console.log works that way. it was complete surprise for me.

**Comment by dolphin-wood** [comment]
Not sure if consoles behave the same on all browsers. But at least on Chrome it is:

![image](https://user-images.githubusercontent.com/6022672/33435725-3fcbd8ea-d626-11e7-9444-bcf61ed8cd07.png)

🙃

**Comment by Okami92** [comment]
Yeah, wow. I'm sure I will have it on my mind for the rest of my career as web developer :)
