### ISSUE TITLE
How to add scroll shadow correctly?

### ISSUE THREAD

**Issue by hongbo-miao** [idiotWu/react-smooth-scrollbar#26]
The first demo is based on Roman Komarov's [blog](http://kizu.ru/en/fun/shadowscroll/).
<kbd>[Online demo](https://jsfiddle.net/Hongbo_Miao/09kuocqo/3/)</kbd>

However, when I try to use it with smooth-scrollbar, it does not work well. Any suggestion will be helpful. Thanks
<kbd>[Online demo](https://stackblitz.com/edit/react-yph3bm?file=index.js)</kbd>

**Comment by dolphin-wood** [comment]
Change

```css
.scrollbox:before,
.scrollbox:after
```

to

```css
.scroll-content:before,
.scroll-content:after
```

because `.scroll-content` is the actual scrolling area ;).

By the way, a **VERY** clever approach of shadow!

**Comment by hongbo-miao** [comment]
Wow, works perfect, thank you soooo much!
