### ISSUE TITLE
Scroll to last inserted Chat problem

### ISSUE THREAD

**Issue by tuffboys** [idiotWu/react-smooth-scrollbar#34]
Hi Dolphin Wood, 
I am developing chat system and once I send any message to user how to update state of scrollbar to last chat.
any help will be more helpful for me to resolve this issue
Thanks in Advance

**Comment by monsef123** [comment]
For anyone looking for a solution for this issue, here is my workaround: 
First create a ref to the scrollbar: 
`const ref = useRef();`
`return (`
`<Scrollbar ref={ref}></Scrollbar>`
`);`

Then you can use the ref in a function to scroll to the bottom like so: 

`const scrollToBottom = () => {`
`    if (ref.current) {`
`      ref.current.scrollbar.scrollTop = ref.current.scrollbar.size.content.height;`
`    }`
`  };`

Then you can use it to scroll to bottom whenever a chat message came in.

**Comment by tuffboys** [comment]
Thanks

**Comment by marxyes** [comment]
> scrollToBottom

Thanks for your solution , It works for me too.........
