### ISSUE TITLE
How to get Scrollbar Instance by using Context in child component

### ISSUE THREAD

**Issue by achtzigundsieben** [idiotWu/react-smooth-scrollbar#38]
I´m trying to get an Instance of the Scrollbar by using Context in a child component.
Stripped down everything so my Code is looking like the 2nd method listed ("2. Use Context in child component"), yet all I get is an error:
"TypeError: Cannot read property 'func' of undefined" for the code line: "getScrollbar: React.PropTypes.func"

The first method (using ref in the parent component) is working as it should! 
Am I missing something here? Isn´t the example complete and I need to create the Context first, before using it in the child component? I´m pretty new to react and would love to get some help with this. Thank you guys!

**Comment by Stiljugend** [comment]
import React, { Component } from 'react';
import PropTypes from 'prop-types';
import Scrollbar from 'react-smooth-scrollbar';

class Child extends React.Component {
	static contextTypes = {
		getScrollbar: React.PropTypes.func
	};
	componentDidMount() {
		this.context.getScrollbar((scrollbar) => {
			// ...
		});
	}
	render() {
		return <div> this is child component. </div>;
	}
}

export default class App extends Component {
	render() {
		return (
			<div className="App">
				<Scrollbar
					id={'scroll'}
					damping={0.05}
					ref={c => this.$container = c}
				>
					<Child />
				</Scrollbar>
			</div>
		);
	}
}
