### ISSUE TITLE
Window undefined in a SSR environment

### ISSUE THREAD

**Issue by emil-j-olsson** [idiotWu/react-smooth-scrollbar#39]
Is there any good way to initialise `react-smooth-scrollbar` when window is defined (SSR)? Using the `useEffect` hook looks promising, but the error is produced even when trying to conditionally render `Scrollbar`, any ideas?

The error produced is the following: 

> ReferenceError: window is not defined
>     at Object.<anonymous> (/Users/emilolsson/projects/AutoMat-SSR/react-ssr-setup/node_modules/smooth-scrollbar/dist/smooth-scrollbar.js:1:138)
>     at Module._compile (internal/modules/cjs/loader.js:774:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
>     at Module.load (internal/modules/cjs/loader.js:641:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:556:12)
>     at Module.require (internal/modules/cjs/loader.js:681:19)
>     at require (internal/modules/cjs/helpers.js:16:16)
>     at /Users/emilolsson/projects/AutoMat-SSR/react-ssr-setup/node_modules/react-smooth-scrollbar/dist/react-smooth-scrollbar.js:1:60
>     at Object.<anonymous> (/Users/emilolsson/projects/AutoMat-SSR/react-ssr-setup/node_modules/react-smooth-scrollbar/dist/react-smooth-scrollbar.js:1:339)
>     at Module._compile (internal/modules/cjs/loader.js:774:30)

Thank you!

**Comment by emil-j-olsson** [comment]
```
const hasWindow = typeof window !== 'undefined' ? true : false;

useEffect(() => {
    // ...
}, [hasWindow]);
```

**Comment by zulfarrakk** [comment]
I find this workaround for Next.js:

`import dynamic from 'next/dynamic'`
`const Scrollbar = dynamic(
  () => import('react-smooth-scrollbar'),
  { ssr: false }
);`

but I cannot find a way to get the Scrollbar element in order to add a Listener to it.

**Comment by JunCLi** [comment]
@alezuk 
The way to get the Scrollbar element is to attach a ref to it.

```
const App = () => {
  const scrollRef = React.useRef(null)

  React.useEffect(() => {
    const { scrollbar } = scrollRef.current

    scrollbar.addListener(status => {
      // stuff you want to do in here
    })
  }, [])

  return (
    <Scrollbar ref={scrollRef}>
      // {children}
    </Scrollbar>
  )
}
```
