### ISSUE TITLE
When component is rendered or updated dosn't set the limits (x and y) properly

### ISSUE THREAD

**Issue by mario-lemes** [idiotWu/react-smooth-scrollbar#5]
Hey @idiotWu ,

I have been trying the React component and I've found the component it dosn't set the limits properly. When I try to get them I get {x:0, y:0}, it seems that the component is not triggering when the content is rendered.

Because of that I can't set the position of the scrollbar to the bottom when the component is rendered.

**Comment by dolphin-wood** [comment]
Do you have any image in your scrollable contents? If so you'd better specify images width and height in order to get correct size of contents, or you're not able to get right size until images have loaded.

Here's some discussions on stackoverflow: http://stackoverflow.com/questions/32367204/react-child-node-height-not-correct

**Comment by mario-lemes** [comment]
Hey @idiotWu,

I don't have any image just text. The thing is in the "componentDidUpdate" function after all the content loaded I ask for the limits of the scrollbar viar refs but even in the last update when there is already content I get {x:0, y:0}. However, when I make scroll and in the function listener that I set previously I'm able to get the limits properly {x:0, y:1235}.

Is like the limits is not set before a while, I don't know exactly.

Thanks for your help!

**Comment by dolphin-wood** [comment]
That's strange, could you please show me any demo about this?

**Comment by mario-lemes** [comment]
I found that the problem is related to this.... http://stackoverflow.com/questions/26556436/react-after-render-code

I don't know if you can make an extra check when the content is properly painted by the browser an then trigger the scrollbar component to get all the values properly set.

Cheers!

PS: I have been trying another [scroll component](https://github.com/smikhalevski/react-scroll-box) and in this I get right away the proper offsets of the trackbac and limits of the viewport. Maybe can help you.

PS2: I'm not able to make an example in JSBin I can't add the react-smooth-scrollbar or I don't know how to do it. I would appreciate if you can provide me some berebone there to make a good example of what is happening.

**Comment by mario-lemes** [comment]
Hey @idiotWu,

I just fixed! I call to instance.update(false) in componentDidUpdate() before to get the limits. Hence forcing doing the call in sync way the component wait till the content is painted and then I can have the proper value of the scrollbar limit!

For me you can close this thread, I hope this help to other who deal with this problem!

Thans for all your help.

**Comment by dolphin-wood** [comment]
Great! 

Now I know why this problem occurs! Take a look at [smooth-scrollbar/init_scrollbar.js#L22](https://github.com/idiotWu/smooth-scrollbar/blob/master/src/internals/init_scrollbar.js#L22), I just init scrollbars asynchronously, so you're not able to get to accurate size of contents. I'll fix it right away, thanks buddy!

**Comment by dolphin-wood** [comment]
This issue should be fixed in smooth-scrollbar@6.1.2 😃

**Comment by mario-lemes** [comment]
Hey @idiotWu ,

That sounds great, master!
