### ISSUE TITLE
Unknown prop

### ISSUE THREAD

**Issue by aight8** [idiotWu/react-smooth-scrollbar#7]
``` JS
vendor.bundle.js:9431 Warning: Unknown prop `fricton` on <section> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in section (created by r)
    in r (created by Scrollarea)
    in Scrollarea (created by Collector)
    in div (created by Collector)
    in div (created by Collector)
```

**Comment by dolphin-wood** [comment]
The `friction` option has been replaced by `damping` since smooth-scrollbar@6.2, you should have seen [a deprecated warning in console](https://github.com/idiotWu/smooth-scrollbar/blob/develop/src/internals/init-options.js#L52) if you've updated to v6.2+ ;)

**Comment by aight8** [comment]
Ah thanks I missed that deprecated message :)
