### ISSUE TITLE
Get Scrollbar Instance

### ISSUE THREAD

**Issue by upq** [idiotWu/react-smooth-scrollbar#8]
any way to get scrollbar instance other than wrapping with another component? Im trying to get it to scroll to bottom on update.

**Comment by dolphin-wood** [comment]
So your `<Scrollbar />` component goes to the first class? Then you should use `context` within your children components like the [2nd method](https://github.com/idiotWu/react-smooth-scrollbar#get-scrollbar-instance) listed in readme.

**Comment by upq** [comment]
Im using the first method actually thats what I need but all instance methods are undefined if I use ref dierctly on ```<Scrollbar />```

**Comment by dolphin-wood** [comment]
Can you show me some of your codes?

**Comment by dolphin-wood** [comment]
Closed as no response.
